export const LANGUAGES = [
  { code: 'en', label: 'English', nativeName: 'English', flag: '🇺🇸', voiceSupport: true, textSupport: true },
  { code: 'es', label: 'Spanish', nativeName: 'Español', flag: '🇪🇸', voiceSupport: true, textSupport: true },
  { code: 'fr', label: 'French', nativeName: 'Français', flag: '🇫🇷', voiceSupport: true, textSupport: true },
  { code: 'de', label: 'German', nativeName: 'Deutsch', flag: '🇩🇪', voiceSupport: true, textSupport: true },
  { code: 'ja', label: 'Japanese', nativeName: '日本語', flag: '🇯🇵', voiceSupport: true, textSupport: true },
  { code: 'zh', label: 'Chinese', nativeName: '中文', flag: '🇨🇳', voiceSupport: true, textSupport: true },
  { code: 'hi', label: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', voiceSupport: true, textSupport: true },
  { code: 'ar', label: 'Arabic', nativeName: 'العربية', flag: '🇸🇦', voiceSupport: true, textSupport: true },
  { code: 'ru', label: 'Russian', nativeName: 'Русский', flag: '🇷🇺', voiceSupport: true, textSupport: true },
  { code: 'pt', label: 'Portuguese', nativeName: 'Português', flag: '🇵🇹', voiceSupport: true, textSupport: true },
  { code: 'it', label: 'Italian', nativeName: 'Italiano', flag: '🇮🇹', voiceSupport: true, textSupport: true },
  { code: 'ko', label: 'Korean', nativeName: '한국어', flag: '🇰🇷', voiceSupport: true, textSupport: true },
  { code: 'nl', label: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱', voiceSupport: true, textSupport: true },
  { code: 'pl', label: 'Polish', nativeName: 'Polski', flag: '🇵🇱', voiceSupport: true, textSupport: true },
  { code: 'tr', label: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷', voiceSupport: true, textSupport: true },
  { code: 'sv', label: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪', voiceSupport: true, textSupport: true },
  { code: 'da', label: 'Danish', nativeName: 'Dansk', flag: '🇩🇰', voiceSupport: true, textSupport: true },
  { code: 'fi', label: 'Finnish', nativeName: 'Suomi', flag: '🇫🇮', voiceSupport: true, textSupport: true },
  { code: 'no', label: 'Norwegian', nativeName: 'Norsk', flag: '🇳🇴', voiceSupport: true, textSupport: true },
  { code: 'th', label: 'Thai', nativeName: 'ไทย', flag: '🇹🇭', voiceSupport: true, textSupport: true },
  { code: 'vi', label: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳', voiceSupport: true, textSupport: true },
  { code: 'id', label: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩', voiceSupport: true, textSupport: true },
  { code: 'ms', label: 'Malay', nativeName: 'Bahasa Melayu', flag: '🇲🇾', voiceSupport: true, textSupport: true },
  { code: 'uk', label: 'Ukrainian', nativeName: 'Українська', flag: '🇺🇦', voiceSupport: true, textSupport: true },
  { code: 'cs', label: 'Czech', nativeName: 'Čeština', flag: '🇨🇿', voiceSupport: true, textSupport: true },
  { code: 'el', label: 'Greek', nativeName: 'Ελληνικά', flag: '🇬🇷', voiceSupport: true, textSupport: true },
  { code: 'ro', label: 'Romanian', nativeName: 'Română', flag: '🇷🇴', voiceSupport: true, textSupport: true },
  { code: 'hu', label: 'Hungarian', nativeName: 'Magyar', flag: '🇭🇺', voiceSupport: true, textSupport: true },
  { code: 'he', label: 'Hebrew', nativeName: 'עברית', flag: '🇮🇱', voiceSupport: true, textSupport: true },
  { code: 'bn', label: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩', voiceSupport: false, textSupport: true },
  { code: 'ta', label: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳', voiceSupport: false, textSupport: true },
  { code: 'te', label: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳', voiceSupport: false, textSupport: true },
  { code: 'mr', label: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳', voiceSupport: false, textSupport: true },
  { code: 'ur', label: 'Urdu', nativeName: 'اردو', flag: '🇵🇰', voiceSupport: false, textSupport: true },
  { code: 'fa', label: 'Persian', nativeName: 'فارسی', flag: '🇮🇷', voiceSupport: false, textSupport: true },
  { code: 'sw', label: 'Swahili', nativeName: 'Kiswahili', flag: '🇰🇪', voiceSupport: false, textSupport: true },
  { code: 'af', label: 'Afrikaans', nativeName: 'Afrikaans', flag: '🇿🇦', voiceSupport: true, textSupport: true },
  { code: 'ca', label: 'Catalan', nativeName: 'Català', flag: '🇪🇸', voiceSupport: false, textSupport: true },
  { code: 'hr', label: 'Croatian', nativeName: 'Hrvatski', flag: '🇭🇷', voiceSupport: false, textSupport: true },
  { code: 'sk', label: 'Slovak', nativeName: 'Slovenčina', flag: '🇸🇰', voiceSupport: false, textSupport: true },
];

export const LANGUAGE_MAP = Object.fromEntries(LANGUAGES.map((l) => [l.code, l.label]));

/** BCP-47 tags for Web Speech API (SpeechRecognition + SpeechSynthesis) */
export const SPEECH_RECOGNITION_LANG = {
  en: 'en-US', es: 'es-ES', fr: 'fr-FR', de: 'de-DE',
  ja: 'ja-JP', zh: 'zh-CN', hi: 'hi-IN', ar: 'ar-SA',
  ru: 'ru-RU', pt: 'pt-BR', it: 'it-IT', ko: 'ko-KR',
  nl: 'nl-NL', pl: 'pl-PL', tr: 'tr-TR', sv: 'sv-SE',
  da: 'da-DK', fi: 'fi-FI', no: 'nb-NO', th: 'th-TH',
  vi: 'vi-VN', id: 'id-ID', ms: 'ms-MY', uk: 'uk-UA',
  cs: 'cs-CZ', el: 'el-GR', ro: 'ro-RO', hu: 'hu-HU',
  he: 'he-IL', af: 'af-ZA',
};

export const SPEECH_SYNTHESIS_LANG = {
  en: 'en-US', es: 'es-ES', fr: 'fr-FR', de: 'de-DE',
  ja: 'ja-JP', zh: 'zh-CN', hi: 'hi-IN', ar: 'ar-SA',
  ru: 'ru-RU', pt: 'pt-BR', it: 'it-IT', ko: 'ko-KR',
  nl: 'nl-NL', pl: 'pl-PL', tr: 'tr-TR', sv: 'sv-SE',
  da: 'da-DK', fi: 'fi-FI', no: 'nb-NO', th: 'th-TH',
  vi: 'vi-VN', id: 'id-ID', ms: 'ms-MY', uk: 'uk-UA',
  cs: 'cs-CZ', el: 'el-GR', ro: 'ro-RO', hu: 'hu-HU',
  he: 'he-IL', af: 'af-ZA',
};
